### ISSUE TITLE
Nexus 3.77.1 fails to boot

### ISSUE THREAD

**Issue by fmotalleb** [sonatype-nexus-community/nexus-repository-composer#177]
nexus fails to boot (it boots but wont let anything happen)
With error:
```
WARN  [qtp628307077-681] *UNKNOWN org.sonatype.nexus.rapture.internal.state.StateComponent - Failed to get state from com.google.inject.internal.InjectorImpl$1 (ignored)
java.lang.IllegalStateException: nx-repository-view-composer-*-delete already exists
```
tried to disable composer-community plugin but failed too boot because i have a group repository
- disabled the composer plugin in nexus.properties
- done changes in `/opt/sonatype/nexus/system/org/sonatype/nexus/assemblies/nexus-core-feature/3.77.1-01/nexus-core-feature-3.77.1-01-features.xml`

**Comment by fmotalleb** [comment]
Temporarily resolved the issue by removing the default composer plugin

Mounted an empty directory instead of the plugin directory, but  it's not a stable approach 
```yaml
services:
  nexus:
    image: "sonatype/nexus3:${NEXUS_VERSION:-3.77.1}-java${NEXUS_JRE_VERSION:-17}-${NEXUS_BASE:-ubi}"
    restart: always
    environment:
      - NEXUS_SECRETS_KEY_FILE=/nexus-data/secret
    networks:
      - webserver_bridge
    volumes:
      - "./data/nexus/deploy:/opt/sonatype/nexus/deploy"
      - "./data/nexus-data:/nexus-data"
      - "./empty:/opt/sonatype/nexus/system/com/sonatype/nexus/plugins/nexus-repository-composer"
```
